[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seismic-slope-disp"
version = "0.1.0"
description = "Compilation of python codes to calculate seismic slope displacement based on semi-empirical approaches"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["src"]